/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EnergyVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CREDIT_PER_TOKEN"
      | "charge"
      | "quoteEnergyCredit"
      | "token"
      | "treasury"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EnergyCharged"): EventFragment;

  encodeFunctionData(
    functionFragment: "CREDIT_PER_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "charge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteEnergyCredit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CREDIT_PER_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "charge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteEnergyCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace EnergyChargedEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenAmount: BigNumberish,
    energyCredit: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenAmount: bigint,
    energyCredit: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenAmount: bigint;
    energyCredit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EnergyVault extends BaseContract {
  connect(runner?: ContractRunner | null): EnergyVault;
  waitForDeployment(): Promise<this>;

  interface: EnergyVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CREDIT_PER_TOKEN: TypedContractMethod<[], [bigint], "view">;

  charge: TypedContractMethod<
    [tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  quoteEnergyCredit: TypedContractMethod<
    [tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CREDIT_PER_TOKEN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "charge"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "quoteEnergyCredit"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EnergyCharged"
  ): TypedContractEvent<
    EnergyChargedEvent.InputTuple,
    EnergyChargedEvent.OutputTuple,
    EnergyChargedEvent.OutputObject
  >;

  filters: {
    "EnergyCharged(address,uint256,uint256)": TypedContractEvent<
      EnergyChargedEvent.InputTuple,
      EnergyChargedEvent.OutputTuple,
      EnergyChargedEvent.OutputObject
    >;
    EnergyCharged: TypedContractEvent<
      EnergyChargedEvent.InputTuple,
      EnergyChargedEvent.OutputTuple,
      EnergyChargedEvent.OutputObject
    >;
  };
}
